# Generated by Django 5.1 on 2024-09-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('I', 'iphone'), ('Iw', 'i-watch'), ('A', 'airPods')], default='I', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='skin',
            field=models.CharField(choices=[('BK', 'Black'), ('RD', 'Red'), ('WH', 'White'), ('PK', 'Pink')], default='R', max_length=2),
            preserve_default=False,
        ),
    ]
